version: "3.8"

services:
    frontend_web:
        container_name: AreaFrontWeb
        build:
          context: ./client
          dockerfile: Dockerfile
        ports:
          - "8081:8081"
        volumes:
          - apk-volume:/usr/app/src/mobile
        depends_on:
          - frontend_mobile
          - backend
    frontend_mobile:
        container_name: AreaFrontMobile
        build:
          context: ./mobile
          dockerfile: Dockerfile
        volumes:
          - apk-volume:/usr/app/mobile
    backend:
        container_name: AreaBack
        build:
          context: ./server
          dockerfile: Dockerfile
        ports:
          - "8080:8080"

volumes:
  apk-volume:
